/**
 * Thinking noise lookup table. Owner: D (Block D3 step 12).
 *
 * Maps orchestrator directive types to pre-rendered thinking noise clips in
 * public/audio/. Use this before the first real AI audio chunk arrives to
 * fill the silence while Gemini + ElevenLabs are working.
 *
 * Clips are generated by: npx tsx scripts/generate-thinking-noises.ts
 *
 * Usage (browser-side, in the frontend component that drives audio):
 *   const clip = getThinkingNoiseUrl(directive.type);
 *   if (clip) audioElement.src = clip;
 *
 * Usage (for latency masking in the turn loop):
 *   playThinkingNoise(directive.type);   ← plays the clip immediately
 *   // then start streaming real audio from ElevenLabs
 */

"use client"; // Browser only — this file plays audio in the browser.

import type { DirectiveType } from "@/lib/types";

// ── URL map ──────────────────────────────────────────────────────────────────
//
// Next.js serves everything in public/ at the root path, so
// public/audio/confused-hmm.mp3 → /audio/confused-hmm.mp3.

export const THINKING_NOISE_URLS: Record<DirectiveType | "default", string> = {
  PROBE:   "/audio/confused-hmm.mp3",    // confused "hmm?" — probing question coming
  DEEPEN:  "/audio/curious-oh.mp3",      // curious "oh—" — about to go deeper
  ADVANCE: "/audio/thinking-wait.mp3",   // soft "wait—" — transitioning forward
  WRAP_UP: "/audio/thinking-um.mp3",     // natural "um..." — winding down
  default: "/audio/thinking-wait.mp3",   // fallback for any unmapped directive
};

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns the URL for the thinking noise clip that best matches a directive type.
 * Falls back to the default "wait—" clip if the directive isn't specifically mapped.
 */
export function getThinkingNoiseUrl(directive: DirectiveType): string {
  return THINKING_NOISE_URLS[directive] ?? THINKING_NOISE_URLS.default;
}

/**
 * Browser-side: plays the appropriate thinking noise clip immediately.
 * Call this as soon as the orchestrator emits a directive, before real audio starts.
 *
 * @param directive - The directive type from the orchestrator (PROBE, DEEPEN, etc.)
 * @returns The HTMLAudioElement, so the caller can call .pause() if needed.
 */
export function playThinkingNoise(directive: DirectiveType): HTMLAudioElement {
  const url = getThinkingNoiseUrl(directive);
  const audio = new Audio(url);
  audio.play().catch((err) => {
    // Browsers block autoplay without prior user interaction — this is expected
    // on first load but should not happen mid-conversation.
    console.warn("[thinkingNoises] Could not autoplay:", url, err.message);
  });
  return audio;
}
